version: 2

defaults: &defaults
  working_directory: /usr/src/app
  docker:
    - image: banian/node-headless-chrome

jobs:
  install:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

  lint:
    <<: *defaults
    steps:
      - run:
          name: ESLint
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - run:
          name: Build Fixtures
          command: yarn build-fixtures

  test:
    <<: *defaults
    steps:
      - run:
          name: Test
          command: yarn jest test/

  release:
    <<: *defaults
    steps:
      - run:
        name: release
        command: |
          if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            ./scripts/release-edge
          fi

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install

      - lint:
          requires:
            - install

      - build:
          requires:
            - install

      - test:
          requires:
            - build

      - release:
          requires:
            - build
            - lint
            - test
